version: '3'

services:

  redis:
    image: redis

  flower:
    image: puckel/docker-airflow:1.10.6
    restart: always
    depends_on:
      - redis
    environment:
      - EXECUTOR=Celery
    ports:
      - '5555:5555'
    command: flower

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data/pgdata

  webserver:
    image: puckel/docker-airflow:1.10.6
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - LOAD_EX=n
      - EXECUTOR=Celery
      - FERNET_KEY=HGx0vUTeKnO3nikOyOHqSzM8_9e3jPZqPVXIwPpS7QU=
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
    ports:
      - '8080:8080'
    command: webserver
    healthcheck:
      test: ['CMD-SHELL', '[ -f /usr/local/airflow/airflow-webserver.pid ]']
      interval: 30s
      timeout: 30s
      retries: 3

  scheduler:
    image: puckel/docker-airflow:1.10.6
    restart: always
    depends_on:
      - webserver
    environment:
      - LOAD_EX=n
      - EXECUTOR=Celery
      - FERNET_KEY=HGx0vUTeKnO3nikOyOHqSzM8_9e3jPZqPVXIwPpS7QU=
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
    command: scheduler
    healthcheck:
      test: ['CMD-SHELL', '[ -f /usr/local/airflow/airflow-scheduler.pid ]']
      interval: 30s
      timeout: 30s
      retries: 3

  worker:
    image: puckel/docker-airflow:1.10.6
    restart: always
    depends_on:
      - scheduler
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
    environment:
      - EXECUTOR=Celery
      - FERNET_KEY=HGx0vUTeKnO3nikOyOHqSzM8_9e3jPZqPVXIwPpS7QU=
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    command: worker