version: '3'
services:

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data/pgdata

  webserver:
    image: puckel/docker-airflow:1.10.6
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - FERNET_KEY=HGx0vUTeKnO3nikOyOHqSzM8_9e3jPZqPVXIwPpS7QU=
    volumes:
      - ./dags:/usr/local/airflow/dags
    ports:
      - '8080:8080'
    command: webserver --debug
    healthcheck:
      test: ['CMD-SHELL', '[ -f /usr/local/airflow/airflow-webserver.pid ]']
      interval: 30s
      timeout: 30s
      retries: 3

  scheduler:
    image: puckel/docker-airflow:1.10.6
    restart: always
    depends_on:
      - postgres
      - webserver
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - FERNET_KEY=HGx0vUTeKnO3nikOyOHqSzM8_9e3jPZqPVXIwPpS7QU=
    volumes:
      - ./dags:/usr/local/airflow/dags
    command: scheduler
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-scheduler.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
